### ISSUE TITLE
Muparser should be integrated via Conan

### ISSUE THREAD

**Issue by aschaeffer** [inexorgame/inexor-core#333]
muparser fast math parser library: https://github.com/beltoforion/muparser

**Comment by a-teammate** [comment]
Imo we should add it as prebuilt lib to the platform repo.

Currently our Dependency system is based on the package managers on linux + prebuilt Visual Studio libs on windows.
Furthermore on Linux for some libs which aren't in any pm we fall back to providing the prebuilt libs ourselves in the platform repo.

We do this bc we don't want the user to built any lib himself which costs built-time (and is "harder" to get going, since you need to provide the build-chain for the dependencies as well sometimes).
However this comes with the costs of compiler-support, more network-traffic requirements and lastly also less optimizations (in case you need to work-around githubs space requirements by uploading less complete libs).

The optimal solution would be to move to conan (which would be the "provide the build-chain for all dependencies" path but with the addition to support caching of prebuilt libs not only on servers but also globally on your local pc).

Adding muparser as submodule is a semi-step towards conan.
So if we do that we better get most deps covered by conan, but in the main-time we should use the usual path.

**Comment by aschaeffer** [comment]
muparser is available in Ubuntu 16.04:
* package: libmuparser2v5
* version: 2.2.3-6

**Comment by aschaeffer** [comment]
https://github.com/ArashPartow/exprtk

**Comment by ArashPartow** [comment]
More 'parser' options can be found here: 

https://github.com/ArashPartow/math-parser-benchmark-project/

**Comment by Croydon** [comment]
@a-teammate After you did integrate OpenGL Mathematics, do we still need this?

**Comment by aschaeffer** [comment]
No, because muparser is not a math library but a math expression parser. The particle system needs it for dynamically compile math formulas represented as a string.

**Comment by Croydon** [comment]
Cross-referencing:

https://github.com/conan-io/wishlist/issues/114
https://github.com/bincrafters/community/issues/543

**Comment by Fohlen** [comment]
This can be done easily now since the conan package exists. Closing.
