### ISSUE TITLE
inexor-flex depends on node-gyp needs python as an end-user dependency

### ISSUE THREAD

**Issue by Fohlen** [inexorgame/inexor-core#456]
Title says it all.
Since python 2.7 is shipped by default on almost every linux and OSX that's not too bad. For windows, that could do it:

https://github.com/felixrieseberg/windows-build-tools

**Comment by Fohlen** [comment]
this is also related to #269 
@terencode I will test wether the above module works, and if so, we can add it to the install instructions for Windows

**Comment by Fohlen** [comment]
will be solved by #277

**Comment by Croydon** [comment]
Is there no way we can get rid of Python as an end-user dep?

**Comment by Fohlen** [comment]
Unless you want to build gyp, a c++ compiler, cmake and python as virtual packages:
no.

**Comment by Croydon** [comment]
Could you please explain the dep tree? Why do we need node-gyp, therefore gyp..?

**Comment by Fohlen** [comment]
grpc, segfault handler build via node-gyp, build via gyp.
gyp is on top of python
gyp also requires a compiler-toolset (what you would call build-essential on Debian)

**Comment by a-teammate** [comment]
node-gyp is used by two dependencies (one which is essential: grpc and one which is really useful: segfault-handler) which are build in c++ rather than js but have node.js bindings.
node-gyp is a meta-build tool comparable to CMake but written in python and **deprecated** (its underlying technology was created by google: GYP).
It's also not python 3.x compatible.

The suggested tool looks pretty good.
You are probably right @Fohlen to let the installer (#277) install the windows-build-tools globally first (it's not becoming apparent though how to use this module to build `npm install` cleanly afterwards, or is it?

**Comment by Fohlen** [comment]
@a-teammate and I agreed to fork segfault-handler and pre-compile it via node-pre-gyp
That way

- we squash bugs in the segfault lib
- get rid of Python as an end dependency

**Comment by Croydon** [comment]
FYI: We are not the only ones annoyed by the situation

https://github.com/nodejs/NG/issues/24#issuecomment-318881285
https://github.com/cmake-js/cmake-js
https://github.com/nodejs/node-gyp/issues/960

**Comment by Fohlen** [comment]
Depending wether we can fix #465 before release, this issue is squashed

**Comment by Fohlen** [comment]
This issue will be resolved by #465 indefinitely

**Comment by a-teammate** [comment]
Since we removed the node-segfault-handler temporarily, we can close this.
As we finished #465 we can enable the handling of segfault errors in native node modules again.
