### ISSUE TITLE
Hackathon: Let's talk about the overall creative direction

### ISSUE THREAD

**Issue by Croydon** [inexorgame/inexor-core#481]
I have noticed that we have different opinions about the overall creative direction of Inexor. Just a few quick example:
 * @Fohlen & @IAmNotHanni don't want to mention anymore that we are a fork of Sauerbraten, while we did that so far from the beginning and imho nothing has changed in this perspective
 * @a-teammate seems to like to go in a very colorful, crazy, "drug-effect-like" environment

So far the overall position seems to have been "Stays sauer" and speaking for myself that is still what I want. I like the general artistic style of Sauerbraten (and the gameplay). These aren't the reasons why I'm thinking that Sauerbraten needs a fork in the first place (the purpose we are all spending time here), nor do I assume that these are the major reasons why Sauerbraten is dying.

We clearly need to talk about these points and the overall creative direction we want to pursue going ahead. We can do this at best when we sitting in the same room, so the upcoming Hackathon seems ideal.

**Comment by IAmNotHanni** [comment]
I have many problems with "Stays Sauer - becomes better".
What really annoys me is that everybody in the Sauer community thinks that Inexor is only aiming to gather their playerbase from Cube2 which is not the case.
Another problem is that many new users won't know Sauer.

**Comment by Fohlen** [comment]
I do partly agree with what @IAmNotHanni but let me strive into a bit more verbose explanation:

- firstly: "Stays Sauer - becomes better" is not to bad. I do like the sauer gameplay, and I very much advise to stick with that
- secondly: "Stays Sauer - becomes better" does already not apply. We're not sauer and we are not aiming to replace sauer. The reason why sauer development, and it's respective community is so fucked up, is mainly because of narrow-minded, "everything should stay as it is" mentality
- I do disagree with catching players from sauerbraten. I said this once: "we are writing a new game here. If you want to join us on this adventure, great! Welcome aboard. If you don't like that, that's fine for me as well"

It is now 3 years of development and we are very close to our first, consumer-testable version of the game. We are an independent game and we don't need to refer to sauer any more. That's my humble opinion on the topic.

**Comment by a-teammate** [comment]
Guys where does all the hate come from? Srsly you are speaking with the wrong people or maybe do the appear to you that way? I've no idea, but plz:
No hateful debate here. Why should you be aggressive towards people just bc they didn't understand something? Oo
And especially people who are hopeful with us? Guys not cool..

I dunno, but maybe you need to ask yourself the question what the real reason is for these feelings and how a constructive way looks to solve it.

Btt:
I did write my opinion already on why we shouldn't refer to sauer too much: https ://github.com/inexorgame/site/commit/bfca8a2144f88a9e989a6e7a46df8e95ad07c1b9#commitcomment-24308305

**Comment by a-teammate** [comment]
Oh and this whole debate is actually pretty much off topic.
Actually not a single comment (including mine) refers in any way to a "creative concept"?
