### ISSUE TITLE
General Project Management Issues

### ISSUE THREAD

**Issue by a-teammate** [inexorgame/inexor-core#558]
We currently lack some stuff, we can do better. For me, this became obvious in the process of the GSoC application and by honestly comparing ourselves with other oss projects.

1. Our documentation is not as clear and friendly as we think
    - in fact, it is often missing "the obvious stuff"
2. Our development team is currently on highly fragile feeds
    - just very few able to do sth when none else is doing sth
    - of course this is also a problem from poor documentation of new systems
    - but also a motivational problem to "strive forward to sth"
        - even when others are currently not helping to assemble the thing together
3.  Our communication should be more transparent
    - also a part of documentation maybe, but also issue/project management
    - also error-communication like "i do not like this", "i dislike that", "i currently can't find a way to"

The good thing is that improving them individually will impact all of them together.

Ideas for the different parts? Besides from "improving the docs" :D 
A Doc-improving party? Bringing back meetings to present individual milestones, working areas, presenting new features to the others?

**Comment by MartinMuzatko** [comment]
As an _almost_ outsider, I know why it is so hard to get started contributing with this project :)

There are multiple interest groups that take care about larger parts of the system.
As I see it, as of now there is:

- core engine (@a-teammate )
- website (@IAmNotHanni @Fohlen  )
- flex (@aschaeffer @Fohlen )
- game content like textures ( @koppiman )
- documentation and licensing (@Croydon )
- UI & CEF (@aschaeffer )
- build/CI (@Croydon @aschaeffer @a-teammate  )

Please correct me if I forgot someone. As an outsider, I have no clue where @movabo or @super-tux  really contributes to. But core engine would be a good guess.
While each I personally think, it is important to have these interest groups, it is hard to see how they depend on each other and how they can work together to deliver one single product - the game.

I think it is important to know who to turn to, for these interest groups. 

I personally would love to be involved with the ingame UI. I also contributed to [ui-prototype](https://github.com/inexorgame/ui-prototype) a while ago, but I have no clue where to go from there. 
What the requirements are, where I get data from (flex?). 

While it is a good thing that these groups can grow independently, there should be a _product owner_ that guides new interested people to where help is really needed and how to contribute. New goals and interest groups can **always** be created, however with only the issues and a bunch of labels, it is hard to tell where contribution is most needed for the desired interest group.

I think a collection of issues is just the start. 
From just the issues, it is hard to tell in which state the project currently is. These individual groups need to have goals defined that can be worked on. (Sprints if you will, if you are coming from a professional development environment)

So the first start, we should document these interest groups and how you can start out to contribute for the individual project goals.

I do not think that more tools like Trello will solve this, but having a good understanding where one can contribute to is valuable for everyone.

**Comment by a-teammate** [comment]
I really like the idea of clearly defining Working Groups.
I agree that it should be always tracked for each working group what its plans are and what is currently doable.
And we need to define for each of them in how far they are connected to other working groups to group up the complete package.

For the recruiting part I imagine the hardest difficulties newcomers need to overcome besides finding out what is doable is the way we expect things to be solved.
I.e. we always look for the elegant solution which does not only solve one, but many issues.
However we do not document that anywhere and neither do we document how to find these solutions. We only say how the code should look like, not the solution.

**Comment by MartinMuzatko** [comment]
Also, we should define and document a "best practice" when to use issues, chat (Telegram/Riot), wiki or hackMD(piratenpad, etc).
There are so many resources to dig into and it is confusing for newcomers to decide which tool to consult for which information.
I'm preparing a wiki page for this and also the working groups. Since you know these groups the best, it would be nice to extend these pages then.

**Comment by Croydon** [comment]
> Our documentation is not as clear and friendly as we think
    in fact, it is often missing "the obvious stuff"

Yes. For example how can I start the game. The reason why a random person new person is here. Or, at the end of the day, we all.

Or can I even run the game? We need to get finally stable in basic building and basic running of the game (aka. a lot can still be broken, but you can do _something_).
Running Inexor doesn't only needs to be possible but damn easy. This is was drives people away. This is what demotivates people the most.

It's very hard to get it running for core members. When you don't even know yet if you like the project at all than you won't invest much time in debugging.


> Ideas for the different parts? Besides from "improving the docs" :D

Next to **missing information**, we also have the problem of **duplicate and outdated information**. Please, please stop duplicating information. I'm sure we have at least 5 places with the **same** basic information how to contribute to our project. This doesn't help, it's contra productive. And it won't get new contributors to us. An easy start into the application (aka. building and running) can hook people to the project because they like what they are seeing. No documentation on this planet can do this.

**Completely** new people also don't care what we have planned. They care about the present state. 

(Our readme has some weird roadmap-ish thing, which I always considered missplaced, we also have milestones for release planing, we have now a flawed roadmap issue (definition of done? same function as milestones and the respective detail/implementation issue itself) and we have laid down in who-knows-how-many wiki pages what our vision overall is. => Information duplicated all over the place + the readme is the first thing new people see, they don't care about our future plan.)

**Comment by a-teammate** [comment]
> Also, we should define and document a "best practice" when to use issues, chat (Telegram/Riot), wiki or hackMD(piratenpad, etc).

what about making that a decision tree?

For that page you'll need
* What defines a working group? Interests? Skills? Both?
* How is the lifetime of a working group defined
   * i.e. when is it important to work in a particular area?

@Croydon 
> Next to missing information, we also have the problem of duplicate and outdated information. 

This is very true, so we this information should be really easy to get. short, precise a good guidance.

I agree that we should strip down the readme.
And of course we need to simplify the setup, but well, that is work. and that is why we have an issue about "project management". To clearify why this work is not done. This issue is not about getting new persons mainly. it is about how to organize ourselves. If we succeed in that, other people can jump in easier, too.

You are right, that we need to clearify the current state and the very next steps in a transparent way is the main point this issue is probably about! (plus together why the very next steps are the very next steps: so we need to clearify the overall vision a bit, too. and also the type of solutions we choose)

**Comment by Croydon** [comment]
> Our documentation is not as clear and friendly as we think
    in fact, it is often missing "the obvious stuff"

Yes. For example, how can I start the game? The reason why a random new person is here. Or, at the end of the day, we all.

Or can I even run the game? We need to get finally stable in basic building and basic running of the game (aka. a lot can still be broken, but you can do _something_).
Running Inexor doesn't only needs to be possible but damn easy. This is was drives people away. This is what demotivates people the most.

It's very hard to get it running for core members. When you don't even know yet if you like the project at all then you won't invest much time in debugging.

____

> Ideas for the different parts? Besides from "improving the docs" :D

Next to **missing information**, we also have the problem of **duplicate and outdated information**. Please, please stop duplicating information. I'm sure we have at least 5 places with the **same** basic information how to contribute to our project. This doesn't help, it's contra productive. And it won't get new contributors to us. An easy start into the application (aka. building and running) can hook people to the project because they like what they are seeing. No documentation on this planet can do this.

**Completely** new people also don't care what we have planned. They care about the present state. 

(Our readme has some weird roadmap-ish thing, which I always considered missplaced, we also have milestones for release planing, we have now a flawed roadmap issue (definition of done? same function as milestones and the respective detail/implementation issue itself) and we have laid down in who-knows-how-many wiki pages what our vision overall is. => Information duplicated all over the place + the readme is the first thing new people see, they don't care about our future plan.)

____

**Working groups.**
I don't like the idea. It's introducing hierarchy which we tried to avoid so far. And it's adding bureaucracy time in which nobody moves the project further. Also this idea isn't endless scalable nor very open to outsiders.

@MartinMuzatko Honest question, why do you need to know **who** is doing what? In my opinion, when you want to contribute you should only need to know **HOW** and **WHERE**. It should be never required to know the internals of an existing team.

Have a look at big repositories, apart from the core team nobody knows anyone.
This leads me to a more general point: I have sometimes the feeling like we treating this still as a small, closed down project. We should stop doing that.

Nobody needs to know that I'm making currently the biggest part of the CI. 
What is the place for suggestions? -> Issues. Anybody who has an opinion on something can comment. People who are actively involved in the part you are talking about, will comment for sure. If you open an issue about CI I will almost certainly comment on it.
How to contribute? -> Open a pull request. People who feel responsible for the project part you touched will get in touch with you for sure. (Of course this involves more like coding standards ect. but to be honest GitHub is placing an obvious message above pull requests, so there is no discovery-problem here).

It's nice if we all have some form of personal contact as well and actually know each other, but this **CAN'T** be a **requirement** for a truely open source project as this is **NOT** **scalable** and doable at all for big projects. And it is not required. Have a look at huge open source projects.

So the answer to 
> I think it is important to know who to turn to, for these interest groups.

is: GitHub issues.

____

Another thing which I'm missing is overall **consistency**. Being it with information (see my first two points) or how decisions are being made.

Sometimes issues are literally open for two years without a decision, others were sometimes only open for hours (or two days or another short time) before some decision was made by someone, preventing more people from commenting.

The same was true for pull requests in the past, but since we do require approvals in Core, Flex and media essentials this got much better here. I don't like at all to add bureaucracy to issues so I guess I don't want to add a completely formal process how decisions are made, but they should be long enough open to give everyone a fair chance to answer and there _**HAS TO(!)**_ be enough input. Obviously, what this means varies strongly. A huge decision about the creative direction should take a long time, because it has such huge and potential irreversible consequences (from a project view point), but a trivial bug fixing issue can be done in relatively short amount of time (if the fix implementation is non-controversial). This requires a good gut feeling and constant self-reflections about the gained experience from previous discussion/decision makings/implementations cycles.

_**And when decisions are made:**_ And they should be made _**nowhere, except on GitHub issues**_, then they need to be replicable and documented. A complete stranger should still understand why and what decisions were made five years later.

It was way too often that even I am didn't know about decisions for a (relative) long time and I literally read everything (all GitHub, all chat messages, all emails, all social media stuff.....) all the time from the beginning.

I also noticed several times, that based on the feedback from few or even a single person, who discovered our project new, people started to **instantly** change readmes, wikis or other stuff. That would be okay, if we have actually learned something new from the feedback and would continue doing things in this specific new way, but often it was like a one-time-thing. For me, that looks impulsive. More consistency, please?

Just one small-ish example: Remember when we wanted to have a wiki template because people were thinking our wiki is a mess? Pretty much every new wiki page doesn't use it anymore. Is this good or bad? Who knows. But it's definitely inconsistent.

I'm sure we would actually drive faster when we take more time for considerations.

This is a marathon, not a sprint.

**Comment by a-teammate** [comment]
> I also noticed several times, that based on the feedback from few or even a single person, who discovered our project new, people started to instantly change readmes, wikis or other stuff. That would be okay, if we have actually learned something new from the feedback and would continue doing things in this specific new way, but often it was like a one-time-thing. For me, that looks impulsive. More consistency, please?

Well, why not act on feedback?
The actual problem is that just small parts get changed when the overall introduction needs a revamp. Thats why we have this issue as well.

### Bureaucracy

> Working groups.
I don't like the idea. It's introducing hierarchy which we tried to avoid so far. And it's adding bureaucracy time in which nobody moves the project further. Also this idea isn't endless scalable nor very open to outsiders.

If we say we are non-hierarchical, but actually do have hidden hierarchies we are not *more open*, but *less transparent*.
The key is to be transparent and open: be transparent about how decisions are made, but at the same time make it open to new people to quickly make an impact in these decisions.

I am speaking about informational hierarchies here and hierarchies which appear just because someone is more involved in a particular topic and gives the main direction.
How to overcome that as a new one? There is currently no structure which resolves such stuff.
The current idea is, that people get more and more involved in a particular aspect, that they become experts there and their knowledge and skills make their opinion matter more in that area.
But there is just no documentation about what areas exist, how many experts already work in that area and how to be one of them.

Issues have limited information. You can not document every and any decision you make as a developer (why did you name it "isgreyscale" and not "iscolorized"?).

### Issue Management
If we could split our issues somehow to be really really tiny, people can actually help somewhere just in the middle of something.

But: how do you still make people feel responsible for the bigger issue? There needs to be a flexible way to document what the overall goal of the issue is, additionally to the minimal sized issues which could allow quick progress (and multiple concurrent working persons).

### Working areas

Yes, I agree that writing people down somewhere in the wiki won't cut it, but that's not the idea.
The idea is to guide and organize people based on their interests.
It is not about a wiki page called "who does what", it is about an organization structure which is modular in such a way, that people immediately know where they want to contribute.

Imagine examplewise a wiki page about the (possible) different stages of development and the working areas when which areas are unblocked under which circumstances. Then for the different working areas clearly listed, what current ideas are, what currently doable mini-issues are and what the result will probably look like in the end.

#### TL:DR:
* smaller issues, please. (but how to still make the bigger issue visible?)
* informational hierarchies always exist, but it should be clear how to overcome them
   * more documentation probably won't solve this, but relevant documentation: a history of decisions to this point + the vision(s)

@MartinMuzatko 
Yes, the structure of flex probably needs some tutorials for some stuff. But imo it is the same issue as in the other areas: normal issues just don't cut it to document the organizational structure, the vision, the already processed steps and the currently doable stuff.

I think the best is currently to ask the experts of an area directly. and probably the best is to do that by arranging a mumble-meetup.
That makes people depend on a tutor, while I think **that** is not really a scalable approach.

**Comment by Fohlen** [comment]
So, hey palls, sorry for being late to the party, I've been a bit busy with life currently.
Here's my 2 cents to the topic. Excuse me if I only gradually comment on things because the conversation has grown quiet large.

## Documentation and why it's so hard to on-board Inexor
I do think our documentation is quiet good and detailed. There's some quirks every now and than, but overall, compared to the size and manpower we have, the docs are amazing! The problem I see is that we lack a "goal", a vision of what we will want to see when the game "finishes". This lack of a common goal also makes it hard to lead somebody to Inexor. How can you understand something we do not even internally have a vision of?

So, to tackle this specific issue, I will sum up what's been said here as a solution, and add a few of my own ideas

- use roadmaps. They're there for a damn reason! They give you an idea of what you want, and the precise thing can grow as you go. No roadmap means no idea of what needs to be done next.
- smaller issues (how to increment something with 5000 lines of code?)
- getting it set up: it's currently our biggest burden, and we will need to rapidly improve in this to attract new contributors. I think we did make quiet good progress on this issue, but it's far from being solved.

## Working groups and responsibility
So, firstly, I would like to comment on responsibility and "personal" contact.

> It's nice if we all have some form of personal contact as well and actually know each other, but this CAN'T be a requirement for a truely open source project as this is NOT scalable and doable at all for big projects. And it is not required. Have a look at huge open source projects.

If you look at old, big, "massive" open source projects, you will notice in all of them:

- they are truly interconnected and almost every contributor knows, or has heard of every other
- somebody is in charge of maintaining things, PERSONALLY
- this is just a social requirement. OSS is a community. Take the community part from it, and it won't work...

I do think working groups are useful for tackling specific problems. e.g we plan a major feature, so we form a working group to tackle this problem. Other than that, I would suggest sticking to maintainer responsibility. These roles could switch every half a year or so, so somebody doesn't get a lonely maniac with all the information and get's crucially important for the future of the project!

## Hierarchy and bureaucracy
Hierarchy sucks. Seriously. And if we look at our internal structure, we have a "absolute minimal hierarchy" needed to run things that require e.g money, but for everything else we have a very lovingly working merocracy. I do see myself and the @inexorgame/founders as competent contact persons who have been around for a long time, but that's it basically. No one of us is power mad, no one of us likes hierarchy, we want to get things done.

About bureaucracy: there has been quiet a lot of talk now how to dense information and add stricter guidelines. I party agree with this in the terms of:

- we need a way to guide ticket development. Who to talk to? When is something considered "done"? How long should a ticket take? How can we speed up things? Seeing somebody making a PR with seemingly no progress is just frustrating, for him as well as for us.
- we should also add a better way to document structural decisions. Either be consistent with hackmd or use GitHub issues.

That's it basically. If we get those right, we will be fine for the next 5 years, probably. Don't overdo it. Don't guideline people and force them to use GitHub issues all the time when all they want is just hack together some idea. Too much is a burden.

## Final resumee
So, here is my proposed solution how we can go on with Inexor structurally

- add ROADMAPS for our projects. This worked really nice for 0.9 release and we should stick with it
- add a "definition of done" and a guideline for contributions that's more transparent than our current one
- add a template for decision process. How and when was something decided? Where? Should we host a monthly or bi-monthly meeting in some kind of form to talk about current issues?
- add a system for maintainers. I propose: we "elect" a person for a certain period of time. If he accepts, he/she will be in final charge of pull requests and releases. This system should also force people to cycle between projects. (maybe half a year is good, dunno). For really big projects such as flex and core this could also be a board of 2 members.
- form "working groups" for specific tasks derived from the roadmap. These should not take longer than a maxima of 2 release periods. Keep things as atomic as possible so they don't get stuck.

With the proposed changes I do think we could get Inexor development a lot more straight.
My last words are, can we come to a conclusion here, maybe add a voting so we can get this issue clarified? Maybe @Croydon can organise it, because he had some clear talent for it in the last few votings?

**Comment by a-teammate** [comment]
TODO in this issue:
- [ ] List all the good ideas
- [ ] Create a specific issue for each of them
- [ ] Make this issue a meta-issue for the specific issues

Probably we should also define a github label "feat:organization"

**Comment by a-teammate** [comment]
An example of (imo) a good overview over a project status (small issues, clearly sorted) https://trello.com/b/lp1XjYaz/ue-viewer

**Comment by a-teammate** [comment]
I think this issue can be closed after this Hackathon.

Currently I assume this to be "fixed", also in the reflection of the number of mumble meetings we had since.
