### ISSUE TITLE
Boost can't be found when using CMake 3.11.0

### ISSUE THREAD

**Issue by IAmNotHanni** [inexorgame/inexor-core#576]
When using `CMake 3.11.0-rc1 (x64)` instead of `CMake 3.10.2 (x64)`  I get the following errors:

https://pastebin.com/zjg6qqdF
https://pastebin.com/LnNYGnEC

Once I downgraded to CMake 3.10.2 x64 everything worked fine. The project map was generated successfully and the project has been compiled. My CMake version was too new.
Add an CMake version check (your version is "too new" and "too old") to the project structure.
Thanks to @Croydon for pointing out that downgrading to CMake 3.10.2 could fix this.

**Comment by Croydon** [comment]
Let's wait if this will be the case in the final CMake 3.11 version. It's okay if it's only the case in the RC.

**Comment by Croydon** [comment]
The boost recipe got an update so this might be solved. @westernheld did run a first test which seems to be successful. I will test this myself in the next days too.

**Comment by Croydon** [comment]
CMake 3.11 is stable now. I will run tests this weekend and update our docker containers if successful.

**Comment by Croydon** [comment]
Our CI just confirmed that this problem is solved with the new Boost recipe.

Furthermore no more warning spam aka:

>
CMake Warning at /usr/share/cmake-3.10/Modules/FindBoost.cmake:801 (message):
  New Boost version may have incorrect or missing dependencies and imported
  targets
Call Stack (most recent call first):
  /usr/share/cmake-3.10/Modules/FindBoost.cmake:907 (_Boost_COMPONENT_DEPENDENCIES)
  /usr/share/cmake-3.10/Modules/FindBoost.cmake:1542 (_Boost_MISSING_DEPENDENCIES)
  cmake/require_thirdparty_libs.cmake:68 (find_package)
  CMakeLists.txt:29 (include)
