### ISSUE TITLE
Figure out Yarn's global structure for packages

### ISSUE THREAD

**Issue by Croydon** [inexorgame/inexor-core#580]
On Windows:
`yarn global add @inexorgame/inexor-flex` adds inexor-flex in `%localappdata%/Yarn/config/global/node_modules/.bin` but not in `%localappdata%/Yarn/bin`

Only %localappdata%/Yarn/bin` is added automatically to %PATH%
so inexor-flex can't be executed from anywhere as it should be..

Figure out how to put inexor-flex in `%localappdata%/Yarn/bin`

And also check if this is working on other platforms.

**Comment by a-teammate** [comment]
Maybe there is a possibility to not install inexorflex globally and still make it somehow convenient to start it.

Because if a user installs inexor via npm on windows, it is probably a dev or experienced with npm. Anyways for those people it would be weird to hide inexorflex somewhere deep down in some hidden folder, if they may actually want to touch it.

The windows installer just puts it in my games/inexorflex and adds that folder to the PATH.
-> even users using the installer don't have flex hidden.

**Comment by Croydon** [comment]
If someone wants to contribute they need to clone the git repository and install flex from there.

Installing it from the npm registry is a lot easier then from git if you don't want to contribute to flex.

This should make it also easier for installers, when they just have to execute `yarn global add @inexorgame/inexor-flex`, since we can't expect git to be installed and zip snapshots from the repository wouldn't be easily updateable.

**Comment by a-teammate** [comment]
Sure, but why should we encourage to install something globally? A local installation is most of the time the thing a novice person should do, I would assume.

Appdata? The scripts of the game should always be in the users reach. not in some dark place where nobody sane would look. How did we start modifying scripts? By checking out a git repo?

**Comment by Fohlen** [comment]
Deprecated because of `go` rewrite of flex.
