### ISSUE TITLE
Proper docs

### ISSUE THREAD

**Issue by Fransje** [inexorgame/inexor-core#90]
Right now the docs (for example the game reference http://sauerbraten.org/docs/game.html ) are very much outdated and not complete. It would be nice to have a complete description of every single game mode, weapon (reload times, damage etc.), and especially of every command that is available. For example the commands /fogdomeclouds or /shrinkmap are not mentioned in the editing reference.

Also, the explanation of some editing aspects and commands could be less mathematical and a little bit more understandable, for example the part about shaders.

The nice thing about this is that it can be done by everybody with game knowledge. You don't need e.g. programming skills for it.

**Comment by a-teammate** [comment]
yeah thats pretty true, sauerbraten's docs suck ass.
I will try to give you a quick overview what has been done already and how this issue will be easier to solve through these: 

Atm @IAmNotHanni comments the codebase, this will already simplify this task a lot i guess. (but of course you are encouraged to help :D )

Furthermore using doxygen ( #87 ) we make sure every new integrated code gets docs "automatically" (when commented correctly)

A lot of the commands probably will change a lot during our refractioning work (especially we will "jsonify" a lot of the current system: the current cubescript configs for e.g. textures models shaders.. will disappear step by step and make place for a system based on JSON-configuration files. ) and probably simplify that stuff (but ofc we are going to documentate them as well)

Imo most of sauerbratens power is hidden below the surface, so its time to explain that stuff a bit and create an easy understandable user-interface. This will probably be easier with @aschaeffer s
work on integrating CEF ( You can easily build guis in HTML5 and Javascript, instead of cubescript)

@koraa has implemented a system called IPC (inter process communication) which allows us to easily integrate new scripting languages calling cubescript commands from withhin other tasks, atm node.js is/was the main goal, since its the most powerful javascript engine. We really need to specify these commands so people actually can work with those other scripting languages.

We pretty much need input from more users, so its really appreciated you open these requests :)

**Comment by Fransje** [comment]
Thanks for the great info, I had come across those impressive names like JSON, CEF etc. on github but now it makes more sense :)

I was actually gonna open an issue on that "easy understandable user-interface", great that this is being dealt with already. Like you say, a lot of Sauer's strength is never even discovered. Newcomers need to know about it!

So if I understand correctly, cubescript is not fully gonna be removed?

And I definitely want to help, in a couple months my exams will be done (hopefully) and then I have oceans of time :)

**Comment by aschaeffer** [comment]
:+1:

Also i suggest we use a documentation generation tool like:

* http://en.wikipedia.org/wiki/DocBook
* http://www.docbook.org/

**Comment by IAmNotHanni** [comment]
One day every line of the Inexor source code will be commented and documented. I love doxygen!

**Comment by Fohlen** [comment]
Integrated with Doxygen!

**Comment by aschaeffer** [comment]
Doxygen => API docs
Proper docs => User documentation

Not even started.

**Comment by Calinou** [comment]
We can use <http://readthedocs.org/> for game documentation.
